spring:
  application:
    name: microservice-customer-movie-feign-with-hystrix
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}