spring:
  application:
    name: microservice-hystrix-turbine2
server:
  port: 8031
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-customer-movie-ribbon-with-hystrix,microservice-customer-movie-feign-with-hystrix,microservice-customer-movie-ribbon-with-hystrix2
  clusterNameExpression: "'default'"
turbine.instanceUrlSuffix.default: ribbon/hystrix.stream
logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG